name: cadenza
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audio_service: ^0.18.17
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.7.2
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.15
  marquee_widget: ^1.2.0
  on_audio_query_forked: ^2.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
